AllCops:
  TargetRubyVersion: 1.9
  DisplayCopNames: true

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# Workaround for https://github.com/bbatsov/rubocop/issues/4740
Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/NumericPredicate:
  Enabled: false

# Default in v0.48.1, but older versions are being used for older Ruby versions, so we set this explicitly here to have the same
# settings on all Ruby versions.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
