AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

Naming/FileName:
  Enabled: false

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Exclude:
    - spec/**/*
Style/NumericPredicate:
  Enabled: false
